name: GitHub Hosted

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Docker
        run: |
          brew update
          brew install docker
          brew install docker-compose
          brew upgrade docker
          docker -v

      - name: Start Docker daemon
        run: |
          sudo /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --pidfile=/var/run/docker.pid --experimental &>/dev/null &

      - name: Wait for Docker daemon
        run: |
          sleep 10

      - name: Check Docker daemon
        run: docker version

      - name: Initialize Git
        continue-on-error: true
        run: |
          git config --global user.name ${{ secrets.GIT_NAME }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git config --global credential.helper store
          echo "https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com" > ~/.git-credentials

      - name: Clone Repository
        continue-on-error: true
        run: |
          git clone -b main https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@${{ secrets.BOT_REPO }} tgenc

      - name: Running Code
        timeout-minutes: 270
        continue-on-error: false
        run: |
          cd tgenc
          docker build . -t svtav1enc
          docker run svtav1enc

      - name: Loop GitHub Hosted
        continue-on-error: true
        run: |
          git clone https://${{ secrets.SUPER_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
          git add looper.txt
          git commit -m "GitHub Hosted: Loop at $(date -u +%D-%T%P)"
          git push -q https://${{ secrets.SUPER_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
