name: GitHub Hosted

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize Git
        continue-on-error: true
        run: |
          git config --global user.name ${{ secrets.GIT_NAME }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git config --global credential.helper store
          echo "https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com" > ~/.git-credentials

      - name: Clone Repository
        continue-on-error: true
        run: |
          git clone -b main https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@${{ secrets.BOT_REPO }} tgenc

      - name: Running Code
        timeout-minutes: 270
        continue-on-error: false
        run: |
          cd tgenc
          docker build -t svtav1enc . --platform=darwin/amd64
          docker run svtav1enc

      - name: Loop GitHub Hosted
        continue-on-error: true
        run: |
          /usr/bin/git clone https://${{ secrets.SUPER_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
          /usr/bin/git add looper.txt
          /usr/bin/git commit -m "GitHub Hosted: Loop at $(date -u +%D-%T%P)"
          /usr/bin/git push -q https://${{ secrets.SUPER_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
          